name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Backend Testing

      # Frontend Testing
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test
      - name: Build Docker image
        working-directory: ./frontend
        run: docker build -t fronth .
